### ISSUE TITLE
Sideways Selfi

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#330] opened 2019-06-14 00:48 UTC
The planter image is saved sideways on the preview page and is also saved in the database as such. 

**To Reproduce**
Get a cheap reject phone that has been dumped on Africa

**Comment by dezidaisy** [comment] 2019-06-18 09:46
It happens when for instance the height is too large. Maybe it could have a frame to crop before saving?

**Comment by deepwinter** [comment] 2019-06-18 21:59
@dezidaisy are you suggesting that Android mis-reports the rotation angle of the photo based off the aspect ration of the captured image?  or some other root cause?    My understanding was that this was a common implementation problem in Android for cheap phones.

**Comment by dezidaisy** [comment] 2019-06-19 05:52
Yes this happened to me on the Jira App on my iPhone but when I cropped the height, it was fine..

**Comment by Davidezrajay** [comment] 2019-07-10 16:03
https://treetracker-production.nyc3.digitaloceanspaces.com/2019.07.10.11.39.49_a5f68c00-d8e6-422e-b16a-e538ac5a6238_IMG_20190710_105806_141417076.jpg

**Comment by Davidezrajay** [comment] 2019-07-17 09:36
https://treetracker-production.nyc3.digitaloceanspaces.com/2019.07.07.20.18.05_f279687a-9229-48c6-990c-d87840a4c850_IMG_20190705_114253_193940485.jpg

Device 238
App version,	1.2.3	
Build 45	
Brand TECNO
Model TECNO WX3	
HArdware mt6580	
TECNO-WX3	
Android	7.0	24

**Comment by Davidezrajay** [comment] 2019-08-13 20:34
https://treetracker-production.nyc3.digitaloceanspaces.com/2019.08.09.10.08.50_bfb5415a-fa7f-4180-9ab8-ff0f35634dd4_IMG_20190809_084848_3663386500706856137.jpg(85 kB)


App version: 1.2.5	
Build: 73	
TECNO MOBILE LIMITED	TECNO	
Model: TECNO CF7
Hardware: mt6739	
TECNO-CF7
Android 8.1.0	27

**Comment by Davidezrajay** [comment] 2019-08-16 06:29
https://treetracker-production.nyc3.digitaloceanspaces.com/2019.07.09.18.27.38_27adec93-19de-4820-8ebd-c8cfd2777a6d_IMG_20190709_161802_-1056322481.jpg

App version: 1.2.5
Build: 73	
Model: Tecno-W3
Hardware:mt6580
Android version: 6.0

**Comment by narkusv** [comment] 2019-09-05 15:50
Probably using new CameraX API would help to solve this problem, since Google advertises that CameraX contain all "hacks" to resolve camera glitches. https://developer.android.com/training/camerax

**Comment by Elforama** [comment] 2019-09-22 16:35
As @narkusv said, the CameraX API should help with this. The square image issue (https://github.com/Greenstand/treetracker-android/issues/394) will add this to the app. Aside from that there is not much we can do without the offending phone. I will close this issue for now since it is covered in the above issue.

**Closed by Elforama** 2019-09-22 16:35 UTC
Labels: android, bug
