### ISSUE TITLE
Fatal Exception: retrofit2.HttpException: HTTP 401 Unauthorized

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#405] opened 2019-12-10 11:24 UTC
Latest version app 1.2.7 (93) has had 71 crashes in the last 71 days. 

Fatal Exception: retrofit2.HttpException: HTTP 401 Unauthorized
       at retrofit2.KotlinExtensions$await$2$2.onResponse + 49(KotlinExtensions.java:49)
       at retrofit2.OkHttpCall$1.onResponse + 129(OkHttpCall.java:129)
       at okhttp3.RealCall$AsyncCall.execute + 206(RealCall.java:206)
       at okhttp3.internal.NamedRunnable.run + 32(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.processTask + 1187(ThreadPoolExecutor.java:1187)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1152(ThreadPoolExecutor.java:1152)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run + 784(Thread.java:784)

**Comment by arunbakt** [comment] 2020-04-16 18:38
Is this obtained from centralized error metrics? Would be useful to know the context on which this crash occurs.

**Comment by arunbakt** [comment] 2020-04-16 19:07
Duplicate of issue https://github.com/Greenstand/treetracker-android/issues/349. 
I am closing this, please re-open if my assessment is wrong.

**Closed by arunbakt** 2020-04-16 19:07 UTC
Labels: bug
