### ISSUE TITLE
App crashing for Samsung version 4.4.4(Samsung Galaxy )

### ISSUE THREAD

**Issue by Surbhi79** [Greenstand/treetracker-android#38] opened 2018-01-29 18:02 UTC
[Kitkat crash.txt](https://github.com/Greenstand/treetracker-android/files/1674694/Kitkat.crash.txt)

**Comment by deepwinter** [comment] 2018-01-29 18:06
1-29 17:26:53.949 1537-1537/org.greenstand.android.TreeTracker.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                        java.lang.RuntimeException: Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
                                                                                            at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
                                                                                            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
                                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
                                                                                            at android.app.ActivityThread.access$1300(ActivityThread.java:130)
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                            at android.os.Looper.loop(Looper.java:137)
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                            at java.lang.reflect.Method.invoke(Method.java:511)
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                                         Caused by: java.lang.ClassNotFoundException: com.google.firebase.provider.FirebaseInitProvider
                                                                                            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
                                                                                            at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
                                                                                            at android.app.ActivityThread.installProvider(ActivityThread.java:4548)
                                                                                            at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)†
                                                                                            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)†
                                                                                            at android.app.ActivityThread.access$1300(ActivityThread.java:130)†
                                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)†
                                                                                            at android.os.Handler.dispatchMessage(Handler.java:99)†
                                                                                            at android.os.Looper.loop(Looper.java:137)†
                                                                                            at android.app.ActivityThread.main(ActivityThread.java:4745)†
                                                                                            at java.lang.reflect.Method.invokeNative(Native Method)†
                                                                                            at java.lang.reflect.Method.invoke(Method.java:511)†
                                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)†
                                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)†
                                                                                            at dalvik.system.NativeStart.main(Native Method)†
01-29 17:26:53.953 367-781/system_process W/ActivityManager:   Force finishing activity org.greenstand.android.TreeTracker.debug/

**Comment by deepwinter** [comment] 2018-03-01 01:35
This was addressed by our patch for 4.4.4 right ?

**Comment by Surbhi79** [comment] 2018-03-01 02:03
Yes.

**Comment by deepwinter** [comment] 2018-03-01 04:07
Fixed in 9ba911679ab68c179e8a8b46dd2003de50dc70a7
Please link PR to issues when possible, thanks!!!

**Closed by deepwinter** 2018-03-01 04:07 UTC
