### ISSUE TITLE
Able to see tree detail screen when clicking inside the Date screen. Overlay issue?

### ISSUE THREAD

**Issue by sebastiangaertner** [Greenstand/treetracker-android#314] opened 2019-05-28 18:53 UTC
While in "Data" screen you can click anywhere and randomly get the "tree detail" info which is supposed to be available only on the "map" screen.

**Comment by Elforama** [comment] 2019-05-29 00:07
I'll look into a fix for this.

**Comment by sebastiangaertner** [comment] 2020-02-16 15:44
Is this fixed?

**Comment by arunbakt** [comment] 2020-05-11 05:17
Hi @sebastiangaertner , I couldn't reproduce it for some reason. When you say 'Data' screen, you are referring to 'Tree Data' screen correct?

**Comment by Elforama** [comment] 2020-11-27 22:49
@sebastiangaertner Is this still an issue?

**Comment by Elforama** [comment] 2021-03-29 01:09
No longer relevant with new 2.0 design

**Closed by Elforama** 2021-03-29 01:09 UTC
