### ISSUE TITLE
Number of trees in user/wallet buttons.

### ISSUE THREAD

**Issue by EngrTaofeek** [Greenstand/treetracker-android#688] opened 2021-11-25 14:53 UTC
UserButton in SelectableItemDetail.kt should fetch total planted number of trees.

**Comment by Elforama** [comment] 2021-11-25 15:54
I think this is a duplicate of this issue https://github.com/Greenstand/treetracker-android/issues/663

**Closed** 2021-11-25 16:00 UTC
