### ISSUE TITLE
RetroFit API Crash

### ISSUE THREAD

**Issue by deepwinter** [Greenstand/treetracker-android#347] opened 2019-06-20 18:33 UTC
This one looks like our API is causing a crash in the app - unhandled http response code when the service is down, or something similar?

Jun 14, 2:27 AM on app version 73
Xiaomi Redmi 6A (cactus), Android 8.1
Report 1

retrofit2.HttpException: 
  at retrofit2.KotlinExtensions$await$2$2.onResponse (KotlinExtensions.java:49)
  at retrofit2.OkHttpCall$1.onResponse (OkHttpCall.java:129)
  at okhttp3.RealCall$AsyncCall.execute (RealCall.java:206)
  at okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
  at java.lang.Thread.run (Thread.java:764)

**Comment by arunbakt** [comment] 2020-05-11 05:56
Has this occurred in recent times?  Is there a centralized log of crash reports that I can get access too to check if this has happened recently?

**Comment by arunbakt** [comment] 2020-05-19 04:52
There are crashes related to retrofit api, not too many though. A couple in the last 30 days. 
Error seems to arise during authentication and from DNS lookup. The master version doesn't have the code that would cause this error any more. I will close this for now and open it if necessary.

Fatal Exception: java.lang.reflect.UndeclaredThrowableException
       at $Proxy2.signIn()
       at org.greenstand.android.TreeTracker.api.RetrofitApi.authenticate(RetrofitApi.kt:4)
       at org.greenstand.android.TreeTracker.api.RetrofitApi.authenticateDevice(RetrofitApi.kt:4)
       at org.greenstand.android.TreeTracker.viewmodels.DataViewModel$startDataSynchronization$1$isAuthenticated$1.invokeSuspend(DataViewModel.kt:1)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:3)
       at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:13)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:1)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:1)
       at 
Caused by java.net.UnknownHostException: Unable to resolve host "treetracker.org": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:126)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
       at java.net.InetAddress.getAllByName(InetAddress.java:1154)
       at okhttp3.Dns$1.lookup(Dns.java:1)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:15)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:3)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:4)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:19)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:1)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:6)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:5)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:22)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:22)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
       at org.greenstand.android.TreeTracker.api.AuthenticationInterceptor.intercept(AuthenticationInterceptor.kt:6)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:40)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
       at okhttp3.RealCall.a(RealCall.java:19)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:2)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:3)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

**Closed by arunbakt** 2020-05-19 04:52 UTC
Labels: crash - analyzing
