### ISSUE TITLE
Location Services 

### ISSUE THREAD

**Issue by Davidezrajay** [Greenstand/treetracker-android#45] opened 2018-02-20 00:59 UTC
FusedLocationApi is deprecated

![image](https://user-images.githubusercontent.com/25363572/36402654-975c0b7a-158c-11e8-941f-6df8645d8fcf.png)
 
LocationServices.FusedLocationApi.requestLocationUpdates(
               mGoogleApiClient, mLocationRequest, this);

Looks like the new API allows one to set the location update interval and target accuracy
what happens.

With the old API, GPS updates to the app go to sleep after the initial fix is got in some cases

**Comment by Davidezrajay** [comment] 2018-02-20 01:00
https://stackoverflow.com/questions/46481789/android-locationservices-fusedlocationapi-deprecated

https://developers.google.com/android/reference/com/google/android/gms/location/FusedLocationProviderClient

https://developer.android.com/training/location/retrieve-current.html

**Comment by habbs19** [comment] 2018-02-24 00:54
What file is this located in?

**Comment by habbs19** [comment] 2018-02-24 01:05
Haha, yes found it.

**Comment by jiacongkylezhu** [comment] 2018-03-01 00:39
Hi all,
I just joined the team. I cloned the project and start looking into it, but I found there was an error so it couldn't run, I tried to fix it as below. Not sure if it is the issue you have discussed here.

I difened the mFusedLocationClient and mLocationCallback, and overided the onLocationResult. 
`mFusedLocationClient = new FusedLocationProviderClient(this);

        // Create a new global location parameters object
        mLocationRequest = LocationRequest.create();
        

        /*
         * Set the update interval
         */
        mLocationRequest.setInterval(LocationUtils.UPDATE_INTERVAL_IN_MILLISECONDS);

        // Use high accuracy
        mLocationRequest.setPriority(LocationRequest.PRIORITY_HIGH_ACCURACY);

        // Set the interval ceiling to one minute
        mLocationRequest.setFastestInterval(LocationUtils.FAST_INTERVAL_CEILING_IN_MILLISECONDS);

        // Set up location call back
        mLocationCallback = new LocationCallback(){
            @Override
            public void onLocationResult(LocationResult locationResult) {
                super.onLocationResult(locationResult);
                mCurrentLocation =locationResult.getLastLocation();
                defineLatLng(mCurrentLocation);
                onLocationChanged(mCurrentLocation);`

I replaced the code discussed above.
![image](https://user-images.githubusercontent.com/18712858/36820974-9da42a60-1ca5-11e8-88f8-57d59a39ab43.png)
 
Ran it on emulator and the accuracy is 20 meters
![image](https://user-images.githubusercontent.com/18712858/36821033-d6069d7a-1ca5-11e8-9c19-12096e956c0d.png)

**Comment by Davidezrajay** [comment] 2018-03-01 00:44
Thanks for joining. If you send me an APK on Slack, I can test it on a phone. We have never had much luck testing on emulators... because it relies on the devices gps???

**Comment by deepwinter** [comment] 2018-03-01 02:15
Hi, thanks for the looking into this ticket.  I am currently resolving it, the problem is that FusedLocationClient does not return a good accuracy all the time.

**Comment by deepwinter** [comment] 2018-03-01 02:19
OK
here's the deal
turns out there's 2 location provider options on Android these days
the old one that is built into Android, and the new google play services one
the old one reports better accuracy numbers than the new one
this is the reason why we were getting these high accuracy reports in the past
i don't believe either approach is better, but they may be calculating accuracy differently, or one may be mis-reporting the accuracy
anyway, i guess we switch for now to the old method
I have also found some articles about how to improve accuracy, by filtering the stream of GPS values returned
this is something to look into when we have some more time

**Comment by deepwinter** [comment] 2018-03-01 04:06
Fixed in 5cb31e1174a943d070c64a2dd961eb66f3895d7b

**Closed by deepwinter** 2018-03-01 04:06 UTC
Labels: priority
